name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use node 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install
        run: |
          npm install
      - name: Demo
        run: |
          echo "::set-env name=FORCE_COLOR::3"
          node cli.js --lhr=.github/reports/exterkamp_dot_codes.json