name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use node 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install
        run: npm install
      - name: Run CLI
        run: node cli.js --lhr=./.github/reports/exterkamp_dot_codes.json